### ISSUE TITLE
App crashes on form (when using Instant Run?)

### ISSUE THREAD

**Issue by amandaloh16** [Date-A-Dog/Date-A-Dog#49]
App crashes on form for me, I can't fill it out like I did the first time

**Comment by amandaloh16** [comment]
Happens on emulator: which most likely Spencer will using to grade so need to pinpoint issue.

Crash reason:  EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
Crash address: 0x18
Process uptime: 1348 seconds

**Comment by amandaloh16** [comment]
You need to be running Nexus 6 P API 24, 1440 x 2560: 560 dpi, API 24, Android 7.0, x86 CPU, 1 GB

Crashed logging into Sally Smith and Amanda Loh, trying to fill out form

**Comment by amandaloh16** [comment]
This is the AVD currently testing form crash with actual android device

**Comment by jammua** [comment]
This may be due to using Instant Run for the emulator. We can continue monitoring this issue and see if it reoccurs when Instant Run is not being used
